version: '3.8'
services:
  backend:
    image: ai-backend
    build: ./BackEnd
   
    ports:
      - "3000:3000"
    container_name: ai-back
    env_file:
      - .env 
   
  
  frontend:
    image: ai-frontend
    build: ./Frontend
    
    ports:
      - "4000:5173"
    container_name: ai-front
    environment:
    - VITE_API_URL=http://backend:3000